### ISSUE TITLE
There is no way of creating a tool check anymore

### ISSUE THREAD

**Issue by TiagoFrossard** [Ethck/Ethck-s-Downtime-Tracking#56]
Whenever I choose a Tool Check on the list "Roll Type", instead of a list of tools being listed on the "Roll choice" list,  I get a generic list with following options: "Kit, Instrument, set, supplies, Tool Utensils".

![image](https://user-images.githubusercontent.com/7585470/111877171-c5a9f080-8980-11eb-909a-3cac9ffcaf94.png)

Old rolls created work properly when loaded, but won't list the tool option needed.
![image](https://user-images.githubusercontent.com/7585470/111877177-cf335880-8980-11eb-8c3f-657370324aa8.png)
![image](https://user-images.githubusercontent.com/7585470/111877192-db1f1a80-8980-11eb-9856-62dad8959b8d.png)

**Comment by Ethck** [comment]
Apologies for this not being clear. I'm surprised that the old version of the activity actually works. The intent is that when selecting the "roll choice" it will search for that name inside of the Actor's items. In this case, if you select "Kit" as the choice it will present any item in the Actor's inventory that is a tool and contains the word "Kit". This is a smart search so that you don't have to hard code the tool(s) required and can just match the right type. Please let me know if you run into any issues setting that up.

**Comment by TiagoFrossard** [comment]
I feel this solution is strange because the DM will have to make hand notes of every table and which tool the player should be using. Also, with the possibility of adding tools for the rolls, the DM could have different DCs for different tools, if needed.

**Comment by TiagoFrossard** [comment]
An example of what I mean: In this case, both tools are rolled with the same DC, but the DM could make herbalism DC higher, for example:
![image](https://user-images.githubusercontent.com/7585470/112774188-39966980-900f-11eb-9f51-9db99936fd70.png)
